# Generated by Django 4.0.3 on 2022-10-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='sold',
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='status',
            field=models.CharField(choices=[('SOLD', 'SOLD'), ('UNSOLD', 'UNSOLD')], default='UNSOLD', max_length=100),
        ),
    ]
