# Generated by Django 4.0.3 on 2022-10-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_remove_automobilevo_sold_automobilevo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='status',
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
